import {
	pgTable,
	uuid,
	varchar,
	text,
	boolean,
	jsonb,
	timestamp,
	index,
} from 'drizzle-orm/pg-core';
import { agents } from './agents.js';
import { agentTriggerTypeEnum } from './agentThreads.js';
// workflows imported lazily to avoid circular: workflows → agents, agentTriggers → agents + workflows
import { workflows } from './workflows.js';

/**
 * Agent triggers — defines what events wake up an agent to spawn a container.
 *
 * Each trigger row represents one subscription:
 *   cron    → config: { schedule: string, timezone?: string }
 *   webhook → config: { secret: string }  (HMAC-SHA256 key for verification)
 *   manual  → config: {}
 *
 * When a trigger fires, AgentRuntimeService spawns a container, passes the
 * trigger payload, and creates a new agent_thread row for that execution.
 *
 * Note: agentTriggerTypeEnum includes 'chat' but only 'cron', 'webhook', and
 * 'manual' are valid here. 'chat' threads are created directly, not via triggers.
 */
export const agentTriggers = pgTable(
	'agent_triggers',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		agentId: uuid('agent_id')
			.notNull()
			.references(() => agents.id, { onDelete: 'cascade' }),
		/** Owner of the agent — denormalized for fast ownership checks */
		ownerId: uuid('owner_id').notNull(),
		/**
		 * Trigger type — reuses agentTriggerTypeEnum.
		 * Valid values here: 'cron' | 'webhook' | 'manual' (not 'chat')
		 */
		kind: agentTriggerTypeEnum('kind').notNull(),
		/** User-visible label for this trigger */
		name: varchar('name', { length: 255 }).notNull(),
		/**
		 * Type-specific configuration object.
		 *
		 * cron:    { schedule: string, timezone?: string }
		 *            e.g. { schedule: "0 9 * * 1-5", timezone: "America/New_York" }
		 *
		 * webhook: { secret: string }
		 *            HMAC-SHA256 key used to verify the X-Hub-Signature-256 header.
		 *            Generated by the backend on creation; shown once to the user.
		 *
		 * manual:  {}
		 */
		config: jsonb('config').notNull().default({}),
		/**
		 * Runtime listening state for app triggers (kind === 'app') — written only by
		 * AppTriggerManager, never by the user. Kept separate from `config` (user intent)
		 * so the listener and the user never clobber each other.
		 *
		 * Shape (AppTriggerState):
		 *   { cursor?, lastPolledAt?, subscriptionId?, expiresAt?, verificationToken?, registeredAt?, ... }
		 *
		 * Empty object for non-app triggers.
		 */
		state: jsonb('state').notNull().default({}),
		/** Whether this trigger is currently active and should fire */
		isEnabled: boolean('is_enabled').notNull().default(true),
		/** Timestamp of the last successful trigger fire (null if never fired) */
		lastFiredAt: timestamp('last_fired_at'),
		/** Optional human description of what this trigger does */
		description: text('description'),
		/**
		 * Optional FK to the workflow this trigger executes when fired.
		 * When set: trigger creates a workflow_run and executes the workflow pipeline.
		 * When null: trigger has no workflow attached (inert until a workflow is assigned).
		 * ON DELETE SET NULL — deleting a workflow disables the trigger's workflow execution
		 * without removing the trigger itself.
		 */
		workflowId: uuid('workflow_id').references(() => workflows.id, { onDelete: 'set null' }),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at').defaultNow().notNull(),
	},
	(table) => [
		index('agent_triggers_agent_id_idx').on(table.agentId),
		index('agent_triggers_owner_id_idx').on(table.ownerId),
		index('agent_triggers_workflow_id_idx').on(table.workflowId),
	],
);
