import { defineConfig } from 'vitepress';

export default defineConfig({
	title: 'Valmis Docs',
	description:
		'Self-hosted AI agent platform — create LLM-powered agents that talk to your apps via chat, messaging channels, and automated workflows.',
	lang: 'en-US',
	// Served as a GitHub Pages project site at https://docs.valm.is,
	// so every asset/link must be prefixed with the repo name.
	base: '/',
	lastUpdated: true,
	head: [['link', { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' }]],
	themeConfig: {
		logo: '/icon.svg',
		nav: [
			{ text: 'Guide', link: '/guide/what-is-valmis' },
			{ text: 'Integrations', link: '/integrations/' },
		],
		search: {
			provider: 'local',
		},
		socialLinks: [{ icon: 'github', link: 'https://github.com/valmishq/valmis' }],
		sidebar: {
			'/guide/': [
				{
					text: 'Introduction',
					items: [
						{ text: 'What is Valmis?', link: '/guide/what-is-valmis' },
						{ text: 'Security Overview', link: '/guide/security' },
						{ text: 'Getting Started', link: '/guide/getting-started' },
					],
				},
				{
					text: 'Installation',
					items: [
						{ text: 'Install with Docker Compose', link: '/guide/installation' },
						{ text: 'Install from Source', link: '/guide/installation-from-source' },
						{ text: 'Configuration Reference', link: '/guide/configuration' },
					],
				},
				{
					text: 'Features',
					items: [
						{ text: 'Agents', link: '/guide/agents' },
						{ text: 'Chat', link: '/guide/chat' },
						{ text: 'Built-in Tools', link: '/guide/tools' },
						{ text: 'Web Browser', link: '/guide/browser' },
						{ text: 'LLM Providers', link: '/guide/llm-providers' },
						{ text: 'Credentials', link: '/guide/credentials' },
						{ text: 'MCP Servers', link: '/guide/mcp-servers' },
						{ text: 'Skills', link: '/guide/skills' },
						{ text: 'Knowledge Base', link: '/guide/knowledge-base' },
						{ text: 'Agent Memory', link: '/guide/memory' },
						{ text: 'Agent-to-Agent Messaging', link: '/guide/agent-to-agent' },
						{
							text: 'Workflows',
							collapsed: true,
							items: [
								{ text: 'Overview', link: '/guide/workflows/' },
								{ text: 'The visual builder', link: '/guide/workflows/builder' },
								{ text: 'Triggers', link: '/guide/workflows/triggers' },
								{ text: 'Agent steps', link: '/guide/workflows/steps' },
								{ text: 'Conditions', link: '/guide/workflows/conditions' },
								{ text: 'Loops', link: '/guide/workflows/loops' },
								{ text: 'Data flow & variables', link: '/guide/workflows/data-flow' },
								{ text: 'Runs & observability', link: '/guide/workflows/runs' },
								{ text: 'Managing from chat', link: '/guide/workflows/agent-chat' },
							],
						},
						{ text: 'Messaging Channels', link: '/guide/channels' },
						{ text: 'API Keys', link: '/guide/api-keys' },
					],
				},
				{
					text: 'Development',
					items: [{ text: 'Testing', link: '/guide/testing' }],
				},
			],
			'/integrations/': [
				{
					text: 'Integrations',
					items: [{ text: 'Overview', link: '/integrations/' }],
				},
				{
					text: 'Triggers (app events)',
					items: [
						{ text: 'Overview', link: '/integrations/triggers/' },
						{ text: 'Gmail', link: '/integrations/triggers/gmail' },
						{ text: 'Outlook / Hotmail', link: '/integrations/triggers/outlook' },
						{ text: 'Google Forms', link: '/integrations/triggers/google-forms' },
						{ text: 'Notion', link: '/integrations/triggers/notion' },
						{ text: 'Slack', link: '/integrations/triggers/slack' },
					],
				},
				{
					text: 'Communication & Bots',
					items: [
						{ text: 'Discord Bot', link: '/integrations/discord-bot' },
						{ text: 'Microsoft Outlook', link: '/integrations/microsoft-outlook' },
						{ text: 'Microsoft Teams', link: '/integrations/microsoft-teams' },
						{ text: 'Pushover', link: '/integrations/pushover' },
						{ text: 'Slack', link: '/integrations/slack' },
						{ text: 'Telegram Bot', link: '/integrations/telegram-bot' },
						{ text: 'Twilio', link: '/integrations/twilio' },
						{ text: 'WhatsApp Business Cloud', link: '/integrations/whatsapp-business' },
					],
				},
				{
					text: 'Customer Support & CRM',
					items: [
						{ text: 'ActiveCampaign', link: '/integrations/activecampaign' },
						{ text: 'Apollo.io', link: '/integrations/apollo' },
						{ text: 'Freshdesk', link: '/integrations/freshdesk' },
						{ text: 'Front', link: '/integrations/front' },
						{ text: 'Gorgias', link: '/integrations/gorgias' },
						{ text: 'Help Scout', link: '/integrations/helpscout' },
						{ text: 'Hunter.io', link: '/integrations/hunter' },
						{ text: 'Intercom', link: '/integrations/intercom' },
						{ text: 'Pipedrive', link: '/integrations/pipedrive' },
						{ text: 'Salesforce', link: '/integrations/salesforce' },
						{ text: 'Zendesk', link: '/integrations/zendesk' },
					],
				},
				{
					text: 'Email & Marketing',
					items: [
						{ text: 'Brevo', link: '/integrations/brevo' },
						{ text: 'Customer.io', link: '/integrations/customer-io' },
						{ text: 'Klaviyo', link: '/integrations/klaviyo' },
						{ text: 'Mailchimp', link: '/integrations/mailchimp' },
						{ text: 'Mailgun', link: '/integrations/mailgun' },
						{ text: 'OneSignal', link: '/integrations/onesignal' },
						{ text: 'Postmark', link: '/integrations/postmark' },
						{ text: 'Resend', link: '/integrations/resend' },
						{ text: 'SendGrid', link: '/integrations/sendgrid' },
					],
				},
				{
					text: 'Analytics',
					items: [
						{ text: 'Amplitude', link: '/integrations/amplitude' },
						{ text: 'Google Analytics (GA4)', link: '/integrations/google-analytics' },
						{ text: 'PostHog', link: '/integrations/posthog' },
					],
				},
				{
					text: 'Productivity & Docs',
					items: [
						{ text: 'Airtable', link: '/integrations/airtable' },
						{ text: 'Asana', link: '/integrations/asana' },
						{ text: 'Cal.com', link: '/integrations/cal-com' },
						{ text: 'Calendly', link: '/integrations/calendly' },
						{ text: 'Canva', link: '/integrations/canva' },
						{ text: 'ClickUp', link: '/integrations/clickup' },
						{ text: 'Coda', link: '/integrations/coda' },
						{ text: 'Confluence', link: '/integrations/confluence' },
						{ text: 'Dropbox', link: '/integrations/dropbox' },
						{
							text: 'Google (Gmail, Calendar, Docs, Sheets, Drive, Forms)',
							link: '/integrations/google',
						},
						{ text: 'Jira', link: '/integrations/jira' },
						{ text: 'Linear', link: '/integrations/linear' },
						{ text: 'Microsoft OneDrive', link: '/integrations/microsoft-onedrive' },
						{ text: 'monday.com', link: '/integrations/monday' },
						{ text: 'Notion', link: '/integrations/notion' },
						{ text: 'Productboard', link: '/integrations/productboard' },
						{ text: 'Smartsheet', link: '/integrations/smartsheet' },
						{ text: 'Tally', link: '/integrations/tally' },
						{ text: 'Todoist', link: '/integrations/todoist' },
						{ text: 'Toggl Track', link: '/integrations/toggl' },
						{ text: 'Trello', link: '/integrations/trello' },
					],
				},
				{
					text: 'Content, CMS & Forms',
					items: [
						{ text: 'Contentful', link: '/integrations/contentful' },
						{ text: 'Directus', link: '/integrations/directus' },
						{ text: 'Ghost', link: '/integrations/ghost' },
						{ text: 'Sanity', link: '/integrations/sanity' },
						{ text: 'Storyblok', link: '/integrations/storyblok' },
						{ text: 'Strapi', link: '/integrations/strapi' },
						{ text: 'Typeform', link: '/integrations/typeform' },
						{ text: 'Webflow', link: '/integrations/webflow' },
						{ text: 'WordPress', link: '/integrations/wordpress' },
					],
				},
				{
					text: 'Design & Collaboration',
					items: [
						{ text: 'Figma', link: '/integrations/figma' },
						{ text: 'Miro', link: '/integrations/miro' },
					],
				},
				{
					text: 'Business & Commerce',
					items: [
						{ text: 'BigCommerce', link: '/integrations/bigcommerce' },
						{ text: 'HubSpot', link: '/integrations/hubspot' },
						{ text: 'Shopify', link: '/integrations/shopify' },
						{ text: 'Square', link: '/integrations/square' },
						{ text: 'Stripe', link: '/integrations/stripe' },
						{ text: 'WooCommerce', link: '/integrations/woocommerce' },
					],
				},
				{
					text: 'Finance, Billing & Payments',
					items: [
						{ text: 'Chargebee', link: '/integrations/chargebee' },
						{ text: 'GoCardless', link: '/integrations/gocardless' },
						{ text: 'Lemon Squeezy', link: '/integrations/lemon-squeezy' },
						{ text: 'Mollie', link: '/integrations/mollie' },
						{ text: 'Paddle', link: '/integrations/paddle' },
						{ text: 'QuickBooks Online', link: '/integrations/quickbooks' },
						{ text: 'Razorpay', link: '/integrations/razorpay' },
						{ text: 'Wise', link: '/integrations/wise' },
						{ text: 'Xero', link: '/integrations/xero' },
					],
				},
				{
					text: 'Developer & Data',
					items: [
						{ text: 'Algolia', link: '/integrations/algolia' },
						{ text: 'Alpha Vantage', link: '/integrations/alpha-vantage' },
						{ text: 'Cloudflare', link: '/integrations/cloudflare' },
						{ text: 'GitHub', link: '/integrations/github' },
						{ text: 'Google Maps', link: '/integrations/google-maps' },
						{ text: 'Meilisearch', link: '/integrations/meilisearch' },
						{ text: 'Pinecone', link: '/integrations/pinecone' },
						{ text: 'SEMrush', link: '/integrations/semrush' },
						{ text: 'SerpApi', link: '/integrations/serpapi' },
						{ text: 'Supabase', link: '/integrations/supabase' },
					],
				},
				{
					text: 'AI & Voice',
					items: [{ text: 'ElevenLabs', link: '/integrations/elevenlabs' }],
				},
				{
					text: 'Social & Web',
					items: [
						{ text: 'Buffer', link: '/integrations/buffer' },
						{ text: 'OpenWeatherMap', link: '/integrations/openweathermap' },
						{ text: 'Reddit', link: '/integrations/reddit' },
					],
				},
				{
					text: 'Smart Home & Generic',
					items: [
						{ text: 'Home Assistant', link: '/integrations/home-assistant' },
						{ text: 'Generic HTTP Auth', link: '/integrations/http' },
					],
				},
			],
		},
		outline: { level: [2, 3] },
		footer: {
			copyright: `© ${new Date().getFullYear()} Valmis · <a href="https://github.com/valmishq/valmis" target="_blank" rel="noopener noreferrer">GitHub</a>`,
		},
	},
});
